### ISSUE TITLE
Platform - Handle long folder names (DMS)

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#114]
![image](https://user-images.githubusercontent.com/32667664/51389851-e9b5e100-1b2d-11e9-811f-bd19b51b2ccf.png)

![image](https://user-images.githubusercontent.com/32667664/51599486-f48ebe00-1eff-11e9-9612-39ec84a13077.png)

use the filter "middle-truncate" to add '...' in the middle of the too long name.
Add a tooltip to show the full name of the folder

https://projects.invisionapp.com/d/main#/console/16395807/342511969/preview

**Comment by jessyca27** [comment]
21/01/2019 : I just did the css for ellipsis but i didn't do tooltip

**Comment by VladislavGritsenko** [comment]
![image](https://user-images.githubusercontent.com/46530080/51808542-31630800-22a6-11e9-8a92-d7adfe6a87e7.png)

i can reproduse the problem :)
did we have tooltip component or i need to create them?

**Comment by Amoki** [comment]
You need to create them!
AS we use vue-bootstrap, you can look at https://bootstrap-vue.js.org/docs/components/modal/#tooltips-and-popovers
