### ISSUE TITLE
Platform - loader à la conversion de l'ifc

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#116]
https://codepen.io/majci23/pen/NqdXvy

![image](https://user-images.githubusercontent.com/32667664/51391055-541c5080-1b31-11e9-825d-e40a51a6102a.png)

![image](https://user-images.githubusercontent.com/32667664/51391016-3d75f980-1b31-11e9-808c-689b4e6da76a.png)

Dans l'idée il faut que l'on remplace l'état "loading" par un petit loader. J'ai joint un petit truc sympa que j'ai piqué sur codpen. C'est une proposition, je l'ai un peu custom de mon coté et j'ai testé sur le prototype.

**Comment by jessyca27** [comment]
border de 5px en primary et roboto. enlever le uppercase de l'exemple codepen

**Comment by jessyca27** [comment]
https://codepen.io/eliortabeka/pen/EXJyPP
