### ISSUE TITLE
Platform - hauteur des ligne du tableau IFC

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#117]
![image](https://user-images.githubusercontent.com/32667664/51391227-cdb43e80-1b31-11e9-9b8d-9bf28c2bca3c.png)

J'ai constaté une différence entre la hauteur des ligne du tableau ifc entre invision et la prod. 
39px pour la prod et 48px sur invision.

**Comment by jessyca27** [comment]
En prod j'ai 47px
