### ISSUE TITLE
Platform -GED curseur doigt sur un dossier

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#131]
![image](https://user-images.githubusercontent.com/32667664/51544854-0f5e2580-1e61-11e9-9820-802e101bd91d.png)

Ça serait cool d'avoir un curseur "doigt" pour signifier qu'on peu cliquer sur le dossier.

**Comment by GabBimdata** [comment]
![image](https://user-images.githubusercontent.com/32667664/51741074-1fab1600-2096-11e9-8781-567f06416d95.png)

Du coup c'est cool mais il me manque le doigt dans la partie de droite "fichier".

**Comment by jessyca27** [comment]
Note : mettre sur le titre aussi, pas que sur le dossier
