### ISSUE TITLE
Platform -GED intégration menu 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#137]
See below for english version

https://projects.invisionapp.com/d/main#/console/16405056/342326777/preview

Dans quelle mesure on peut dors et déjà commencer ce menu avec les features qui existent déjà ? Et peut on créer les autres ? 
Question ouverte ^^ le menu existe déjà mais il faudrait l'étoffer.

**Comment by jessyca27** [comment]
Vu le 25/01/2019 avec Gab : fonctionnalité du menu à développer
- Télécharger
- Renommer
- Supprimer

**Comment by jessyca27** [comment]
RAF : Fermer le menu principal quand les actions de suppression et renommage sont effectués (et fermés).
NB : Les références n'ont pas fonctionné. Les emit non plus...

**Comment by Amoki** [comment]
Sorry for the French discussion!
Here is the English recap:
We want to implement many actions in the DMS directly on each file. Jessyca started to work on it but get stuck at some point. Her work is merged on master.
The menu is here, the action should wort but be the menu is bugged (click responsiveness, etc)

The download action should only be shown for documents. We'll think about folder download in a second time (with local storage, building a zip file and download this zip, similar to Mega.nz service)
https://projects.invisionapp.com/d/main#/console/16395807/343415941/preview

**Comment by VladislavGritsenko** [comment]
i'm sry, but i can't understand what actualy i need to fix)
can you describe for me some key points? it is not clear for now.

**Comment by Amoki** [comment]
Ok!
* On rename, the menu doesn't fully close
* The rename action is always "rename folder" even if we renaming a file
* Go in a subfolder => clic on the menu on an item => the menu is fully open (the menu, the rename menu, and the delete menu)
