### ISSUE TITLE
Platform - model preview dans la carte projet

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#153]
https://projects.invisionapp.com/d/main#/console/16405056/340187191/preview
![image](https://user-images.githubusercontent.com/32667664/51838528-cf86ba80-2306-11e9-91ca-9aff2eb862f8.png)

Le grand jour est arrivé ! Nous allons retravailler la carte "projet" en intégrant un peu mieux le model preview. Je dois voir avec hugo pour changer la couleur du background mise à part ça tout est ok je crois.

**Comment by jessyca27** [comment]
30/01/2019 : 
- afficher l'oeil que quand il y a une maquette
- l'oeil doit rediriger vers le viewer du bâtiment affiché dans la card
