### ISSUE TITLE
Store not fully set when loading from viewer url

### ISSUE THREAD

**Issue by Amoki** [bimdata/platform-old#154]
When loading the viewer page directly from the URL (https://platform-staging.bimdata.io/viewer/cloud/129/project/185/ifc/395), data are not loaded and the customUrl is not detected.
I'm afraid it's more a global problem with data load in components and the router.

**Comment by VladislavGritsenko** [comment]
I have some questions. 
In viewer url we have cloud_id=129. 
When we get clouds from backend i don't see cloud with same id.
![image](https://user-images.githubusercontent.com/46530080/52102626-91cdae80-25f2-11e9-82c3-ff8a7e5cdd08.png)
and project 185 missed to. i'm a little bit confused.

**Comment by Amoki** [comment]
Oh, you may not have access to this cloud and projects! I had you!
