### ISSUE TITLE
Platform - mauvaise url pour accède à la page profil

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#157]
![image](https://user-images.githubusercontent.com/32667664/51852482-77f84700-2326-11e9-8dde-a68a873cca99.png)

Il manque le "/" entre io et profil pour accéder à la page.

**Comment by jessyca27** [comment]
31/01/2019 : tout fonctionne en local mais pas sur staging et sur next...

**Comment by GabBimdata** [comment]
du coup c'est une demande au russe @jessyca27 ?
