### ISSUE TITLE
Plateforme - largeur du bloc arbo

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#173]
![image](https://user-images.githubusercontent.com/32667664/52056088-91d19e00-2561-11e9-93f4-b7e7f67a61db.png)

Possible d'élargir le bloc arbo GED ? Je me suis aperçu que sur un grand écran ça faisait vraiment petit ... désolé.

**Comment by jessyca27** [comment]
01/02/2019 : 350px
