### ISSUE TITLE
Plateforme - ajouter un menu "projets" lorsque l'on est sur une page projet

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#178]
![image](https://user-images.githubusercontent.com/32667664/52057465-5df87780-2565-11e9-8874-a1f0ea29892e.png)

Possible de mettre un bouton pour retourner à la page "projet du cloud" pour retourner sur la page des projets du cloud lorsque l'on est sur dans un projet. Car actuellement peut que retourner sur la page cloud et c'est pas super pratique pour retourner simplement sur la page des projets.

**Comment by jessyca27** [comment]
01/02/2019 : Quand on est sur une page projet uniquement, il faudrait mettre dans le menu principal "Project's clouds" qui serait un lien vers la page des projets du cloud actuel
