### ISSUE TITLE
Plateforme - search component

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#183]
https://projects.invisionapp.com/prototype/cjrkri08r00efrm01ddl7d03v/play  <--- il  faut cliquer sur la loupe

https://projects.invisionapp.com/d/main#/console/16405056/344195822/preview

J'ai remarqué que sur cette page on aurait bien besoin d'une barre de recherche dans la page des cartes projet. J'ai pondu un proto avec une petite animation.

**Comment by GabBimdata** [comment]
@jessyca27 c'est parfait mais c'est possible de réduire le temps de l'animation ?

**Comment by jessyca27** [comment]
Je l'ai passé de 0.35s à 0.25s
