### ISSUE TITLE
Project Invitation process

### ISSUE THREAD

**Issue by Amoki** [bimdata/platform-old#218]
# To invite a user:
https://projects.invisionapp.com/d/main#/console/16395807/347098175/preview
https://api-staging.bimdata.io/doc#/project/projectInvite
roles constants:
100 = ADMIN
50 = User
25 = Guest

redirect_uri is the URL where users will be redirected after they accept the invitation (here, the project url).
(upgrade bimdata-api-client to 3.1.0 to have invitation calls)

# Get user list:
https://api-staging.bimdata.io/doc#/project/getProjectUsers

# get pending invitations:
Comming soon

# Already existing
Jessyca started to work on branch "users-list".  The vuejs part can be redone as you want, but at least the CSS is alrealy here :D

**Comment by VladislavGritsenko** [comment]
![image](https://user-images.githubusercontent.com/46530080/53706653-6847b300-3e3c-11e9-9af2-36fca328bb40.png)
![image](https://user-images.githubusercontent.com/46530080/53706673-801f3700-3e3c-11e9-81fd-9481146f8a80.png)

have an error

**Comment by VladislavGritsenko** [comment]
![image](https://user-images.githubusercontent.com/46530080/53706698-96c58e00-3e3c-11e9-9b0c-26f8033a7519.png)
just 500 :)
