### ISSUE TITLE
Error on new project page

### ISSUE THREAD

**Issue by VladislavGritsenko** [bimdata/platform-old#239]
![image](https://user-images.githubusercontent.com/46530080/53196721-be8d4880-3629-11e9-9248-a2e103c0014e.png)

Problems with map on new empty project page.

**Comment by Amoki** [comment]
Oh yes, we load the map and preview components even if there is no IFC. @GabBimdata, any idea ?

**Comment by benjaminaudet** [comment]
What's the actual state of this issue?
