### ISSUE TITLE
Errors in map component

### ISSUE THREAD

**Issue by VladislavGritsenko** [bimdata/platform-old#241]
![image](https://user-images.githubusercontent.com/46530080/53211368-f9a37200-3651-11e9-8240-e0f59c4e031d.png)
 errors in console when mounted map component

**Comment by Amoki** [comment]
Yep, we plan to improve the location detection to avoid null lat and lng. It just need some very specific API calls. It's on  the roadmap :)

**Comment by benjaminaudet** [comment]
What's the state of this issue?
