### ISSUE TITLE
Plateforme - taille des fonts

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#256]
![image](https://user-images.githubusercontent.com/32667664/53743328-d58a3100-3e9a-11e9-9edf-88ea704217b3.png)

C'est encore de ma faute mais c'est possible de mettre les fonts en 0.8 rem ? (partout ou elles sont en 0.714rem)

**Comment by jessyca27** [comment]
Vu avec gab : mettre en 0.8 uniquement pour la liste utilisateurs
