### ISSUE TITLE
Plateforme - bug suppression d'un user

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#257]
![image](https://user-images.githubusercontent.com/32667664/53743678-ade79880-3e9b-11e9-89cd-0dd7271ea44a.png)

![image](https://user-images.githubusercontent.com/32667664/53743704-ba6bf100-3e9b-11e9-9754-6fb554e5da2e.png)

Possible de reprendre le petit composant de suppression que tu avais fait pour la suppression d'un projet ? (même menu)

**Comment by jessyca27** [comment]
C'est déjà le cas. Il n'est visiblement pas passé sur staging
