### ISSUE TITLE
Plateforme - refresh auto list bloc user 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#261]
![image](https://user-images.githubusercontent.com/32667664/53744228-dc19a800-3e9c-11e9-87e3-75646cefda3a.png)

Pour la suppression / modification / invitation d'un user il faudrait refresh dynamiquement la listes des user.

**Comment by jessyca27** [comment]
Note au 05/03/2019 : Je ne peux pour le moment pas faire l'ajout dynamique car nous n'avons pas encore d'url pour charger la liste des invités :)
