### ISSUE TITLE
Plateforme - hover et clic sur les cartes cloud

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#299]
![image](https://user-images.githubusercontent.com/32667664/54440966-fe80b080-473b-11e9-8ea3-9bcf1c34c8fd.png)
https://projects.invisionapp.com/d/main#/console/16405056/352485158/preview
Suite a des test users Sarah m'a remonté un problème d'UX. En effet actuellement pour accéder au cloud il faut cliquer sur le picto "image" qui en fait à terme permettra de modifier ou ajouter une photo de profil au cloud. 

C'est complètement my bad et pour y remédier il nous faut deux choses : 
1 - pouvoir cliquer sur le titre du cloud (utiliser la petite animation de la doc pour les liens) 
2 - cliquer dans le blanc de la carte (au hover on passerai à un box shadow 20% et au clic accéder au cloud.

Si pas compris je suis à côté :)

**Comment by jessyca27** [comment]
MAJ  25/03/2019 : la modification de l'image du cloud se fera par le menu, comme pour le changement de nom.
