### ISSUE TITLE
Plateforme - modale d'invitation admin bouton accès utilisateurs

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#302]
![image](https://user-images.githubusercontent.com/32667664/54521193-b7c4cd80-496a-11e9-995c-a39691c9cd79.png)

Il faudrait modifier l'opacité du box shadow, actuellement elle est à 8% et il faudrait la passer à 15%.

**Comment by jessyca27** [comment]
MAJ du 18/03/2019 : Lpour le btn user : finalemen on affiche juste le SVG en bleu et on garde le tooltip à l'hover
