### ISSUE TITLE
Plateforme - modale d'invitation admin

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#303]
![image](https://user-images.githubusercontent.com/32667664/54521295-eb9ff300-496a-11e9-808e-1665ac617d35.png)

![image](https://user-images.githubusercontent.com/32667664/54522201-ed6ab600-496c-11e9-998c-16c11c57eec2.png)

https://projects.invisionapp.com/d/main#/console/16405056/352718169/preview

On est pas super iso proto sur la modale d'invitation admin : 

- couleur des bordeurs du champs email
- position du champs email (actuellement il est pas centré) 
- j'ai revu la manière dont on valide ou annule l'invitation c'est possible de faire ça ? 
- les marges dans la liste des admin (et user du coup) ne sont pas respectés
- possible d'avoir un petit effet quand on clique sur la flèche retour ?

**Comment by jessyca27** [comment]
MAJ 18/03/2019 : 
- Couleurs des bordures traités dans l'issue/306
- points 2 et 3 n'existent pas (pas à faire)
