### ISSUE TITLE
Plateforme - couleur des border à la saisie

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#306]
![image](https://user-images.githubusercontent.com/32667664/54524109-61a75880-4971-11e9-9338-6944caaa2b66.png)
![image](https://user-images.githubusercontent.com/32667664/54524138-7257ce80-4971-11e9-8e26-689e8a559dbe.png)

Possible de mettre partout la primary en couleur de border lorsque le de la saisie ?

**Comment by jessyca27** [comment]
Note : que pour les listes d'users et pas pour les choiceList
