### ISSUE TITLE
Plateforme - default cloud

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#317]
![image](https://user-images.githubusercontent.com/32667664/54609792-ebc7ed80-4a53-11e9-80d6-f195e2c0a2df.png)

‘default cloud’ mettre une maj a Default

**Comment by jessyca27** [comment]
@GabBimdata : Je n'ai pas la main dessus, voir avec Hugo

**Comment by benjaminaudet** [comment]
Tu veux que je m'en occupe @GabBimdata ?

**Comment by benjaminaudet** [comment]
Ah mais oui c'est côté back lol @Amoki

**Comment by GabBimdata** [comment]
^^
