### ISSUE TITLE
Plateforme - impossible de voir la carte projet alors que je suis user dedans

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#324]
![image](https://user-images.githubusercontent.com/32667664/54768941-91b85b00-4c00-11e9-97eb-27c91b958072.png)

Cloud : gabs cloud
Projet : nouveau test premier projet

Compte : id :gabriel@bimdata.io / ultramarin:89

**Comment by jessyca27** [comment]
26/03/2019 : Je n'ai plus ce problème
