### ISSUE TITLE
Plateforme - comportement menu bloc user 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#333]
![image](https://user-images.githubusercontent.com/32667664/54924552-f0d1e480-4f0c-11e9-9e1d-4b8e4db6f4fc.png)

Possible de faire quelque chose à ce niveau là ? Ou on est condamné à voir le menu de cette manière lorsque je sélectionne le user le plus bas dans la liste ?

**Comment by jessyca27** [comment]
@GabBimdata Je peux tenter une ouverture vers le haut pour le dernier ? Mais par contre je ne pourrais pas te l'ouvrir par dessus en mode ça sort du bloc de la liste... :/

**Comment by GabBimdata** [comment]
@jessyca27 ok ça me va bien :)

**Comment by GabBimdata** [comment]
![image](https://user-images.githubusercontent.com/32667664/55094209-3bdb2b80-50b6-11e9-83d2-1204900ec523.png)

@jessyca27
