### ISSUE TITLE
Plateforme - animation une fois changement de droit

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#335]
![image](https://user-images.githubusercontent.com/32667664/54925075-e06e3980-4f0d-11e9-88d3-e7bed73a6aee.png)

Possible d'ajouter une petite animation au changement de droits d'un utilisateur (genre un petit effet clignotement) pour bien marqué que c'est ok.

**Comment by jessyca27** [comment]
@GabBimdata un exemple ? :/ Tu le veux sur quoi l'effet ?

**Comment by jessyca27** [comment]
y a déjà la pastille qui change actuellement

**Comment by jessyca27** [comment]
Note : si je t'ajoutes la fonctionnalité de validation, ya moyen de tout simplement fermer le sous-menu pour montrer que ça a été pris en compte comme partout ailleurs sur le site ?
