### ISSUE TITLE
Plateforme - ajouter la date dans le place holder d'invitation 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#357]
![image](https://user-images.githubusercontent.com/32667664/55813721-91b7c680-5aed-11e9-98ae-d369ba7abcea.png)

A côté de resend invit peut-on ajouter la date d'invitation ? Lorsqu'elle a été émise ?

**Comment by jessyca27** [comment]
10/04/2019 : A ce jour nous récupérons de l'API, le mail, le role et redirect_uri mais pas de dates pour les users en attente de validation

**Comment by GabBimdata** [comment]
backend dependant
