### ISSUE TITLE
Plateforme - spam clic sur resend invit

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#358]
On a un petit soucis, actuellement si tu spam clic sur  resend ça envoi des mails à l'infini !

**Comment by jessyca27** [comment]
10/04/2019 : Vu avec gab, on affiche un message de succès pour informer l'utilisateur du bon renvoie de l'invitation : https://projects.invisionapp.com/d/main#/console/16405056/357284944/preview

**Comment by GabBimdata** [comment]
@jessyca27 pour le coup je me suis encore spam ^^ il y a une limite ?
