### ISSUE TITLE
Plateforme - créer des cloud 

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#365]
![image](https://user-images.githubusercontent.com/32667664/55945845-dbb6be80-5c4b-11e9-90a7-f997247a0388.png)

Actuellement on peu spam clic et créer une infinité de cloud. Peut on limiter à un seul clic ?

**Comment by jessyca27** [comment]
11/04/2019 : Vu avec Gab --> ajout d'une classe d'erreur quand on créer un cloud dans nom
