### ISSUE TITLE
Revenir à BIMData Connect

### ISSUE THREAD

**Issue by mere-teresa** [bimdata/platform-old#396]
Je me connecte sur https://connect-next.bimdata.io/ ensuite je vais sur la Platform et je suis tranquille.
Quand je clique sur mon username, j'ai un lien "Account Settings" et j'en suis ravie. Je me retrouve sur mon profil. Je cherche BIMData Connect et je ne sais pas où aller.

J'ai fini par cliquer sur Home du chemin d'ariane et le retrouver. Sinon j'ai ragé.

**Comment by Amoki** [comment]
What about opening account settings in a new tab instead of leaving the platform?

**Comment by GabBimdata** [comment]
Si tu as cliqué sur "Account Settings" tu es déjà sur BIMData Connect. @mere-teresa
