### ISSUE TITLE
Plateforme - GED problème avec téléchargement d'un dossier

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#397]
![image](https://user-images.githubusercontent.com/32667664/59691004-a5b13000-91e2-11e9-8ad1-32cda6234181.png)

Actuellement dans le menu de la GED pour un dossier on a la possibilité de le télécharger. Le souci c'est que ça ne marche pas. On a deux choix, soit on laisse la possibilité de le DL en mode zip, soit on à décide de ne pas laisser la possibilité de le DL. 

C'est compliqué comment de pouvoir faire un zip avec le dossier et ses enfants ?

**Comment by Amoki** [comment]
Compliqué:
Générer un zip du dossier parent avec des 50 sous dossier squi ont chacun 3 maquettes, c'est vite très lourd

**Comment by GabBimdata** [comment]
OKi alors solution 2 : nous supprimons "download" du menu du dossier dans la GED. @LrxGaelle
