### ISSUE TITLE
Plateforme - Empty folder should say it's empty in DMS

### ISSUE THREAD

**Issue by benjaminaudet** [bimdata/platform-old#416]
Currently, a opened empty folder looks as follows:

![image](https://user-images.githubusercontent.com/9674694/60191615-e63d2900-9834-11e9-93a8-9e336d112db3.png)

I imagine something like that : 

![image](https://user-images.githubusercontent.com/9674694/60191672-00770700-9835-11e9-9a54-44b14160daf4.png)

If you remember our discussion about users list when it's empty, I imagine something like that without the sad smiley because it has nothing to do in DMS

**Comment by GabBimdata** [comment]
C'est en cours de mon côté. Je vais réfléchir à une manière générique pour l'ensemble des cas ou on affiche soit une liste vide, soit une conteneur sans contenu. @benjaminaudet
