### ISSUE TITLE
Plateforme - Assign a cloud's image

### ISSUE THREAD

**Issue by benjaminaudet** [bimdata/platform-old#417]
![image](https://user-images.githubusercontent.com/9674694/60192028-8bf09800-9835-11e9-8a17-01823540e2a7.png)

We should be able to add an image to a cloud
Is it ready on backend side ? @Amoki 
Do you have any changes on that on mockups ? @GabBimdata

**Comment by GabBimdata** [comment]
Pour le coup rien n'est actuellement prévu côté back @hugo c'est pas prio et je ne pense pas le remonter dans la liste des tâches plateforme ^^ mais c'est bon de l'avoir de côté.
