### ISSUE TITLE
Platform - Rename of cloud/project should auto-select like in DMS

### ISSUE THREAD

**Issue by benjaminaudet** [bimdata/platform-old#418]
Cloud's rename
![image](https://user-images.githubusercontent.com/9674694/60192287-e7bb2100-9835-11e9-8e7e-b6671771d14a.png)

Project's rename
![image](https://user-images.githubusercontent.com/9674694/60192337-f99cc400-9835-11e9-964d-3cf6731f3d94.png)

What do you think about that @GabBimdata ?
If it's okay for you, it's not a big deal for me :)

**Comment by GabBimdata** [comment]
go @benjaminaudet

**Comment by benjaminaudet** [comment]
SHNEL SHNEL SHNEL
