### ISSUE TITLE
Plateforme - Error when trying to invite a user without setting attended rights

### ISSUE THREAD

**Issue by benjaminaudet** [bimdata/platform-old#419]
![image](https://user-images.githubusercontent.com/9674694/60192627-6f089480-9836-11e9-9924-0b4bd9bf1a98.png)

As the error for e-mail, we should say an errors when the rights have not been entered

**Comment by GabBimdata** [comment]
Ouais j'imagine que c'est mieux d'aller au fond de l'idée. :) @benjaminaudet
