### ISSUE TITLE
Plateforme - impossible de supprimer un fichier depuis le menu GED

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#424]
![image](https://user-images.githubusercontent.com/32667664/60675877-c1246800-9e7d-11e9-9872-9fef074e4e1d.png)

Une fois sélectionné depuis la GED, impossible de supprimer un fichier depuis le bouton delete.

**Comment by benjaminaudet** [comment]
Files and folders deletions through the selection and through the dropdown menu are working fine.
The regression seems to have been fixed alone :rocket:
