### ISSUE TITLE
Plateforme - disparition des petits pictos svg dans la GED

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#425]
![image](https://user-images.githubusercontent.com/32667664/60676780-05186c80-9e80-11e9-9461-072cc3a9dafe.png)

Suite aux modifications de @benjaminaudet dans la GED (j'ai l'impression) je constate la disparition des pictos svg dans la GED (selon les extensions de fichier).

**Comment by benjaminaudet** [comment]
Bien curieux de savoir d'où vient le problème

**Comment by GabBimdata** [comment]
c'est la mise à jour de la lib qui a tout cassé @benjaminaudet 

https://github.com/bimdata/platform/commit/57560184717614697c2e3c521ff86178b6c5989b

c'est corrigé sur next
