### ISSUE TITLE
Plateforme - accéder à bimdata connect depuis le user menu

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#427]
![image](https://user-images.githubusercontent.com/32667664/60809748-b0c90180-a18b-11e9-8917-d66994489430.png)

https://projects.invisionapp.com/d/main?origin=v7#/console/16405056/372600964/preview

Suite à la maj d'hugo concernant l'accès aux données du profil il faut qu'on ajoute un accès à bimdata connect depuis la plateforme. J'ai ajouté un lien dans le menu. Tu trouveras ci-joint le picto svg.  
[picto-bimdataconnect.svg.zip](https://github.com/bimdata/platform/files/3367656/picto-bimdataconnect.svg.zip)

**Comment by benjaminaudet** [comment]
BIMData Connect instead of BIMData connect no ?
It's a like a little product that is capitalize at each place we use it right?

**Comment by GabBimdata** [comment]
typo
