### ISSUE TITLE
I can't run the backend

### ISSUE THREAD

**Issue by sotlog** [bimdata/platform-old#465]
Hello,
Every time I try to run the server ("npm run serve"), it shows: "We're sorry... Client not found."
I am giving the right client id e.g.:  "dacedd65-1cd4-44de-9438-887c4a0bbcd3".
Where is the problem? Thanks!

**Comment by Amoki** [comment]
Hi,

By default, the platform uses our staging environment (https://iam-staging.bimdata.io) and you created your app on our "next" environement. You have to replace all `-staging` URLs with `-next` in the .env file.

We'll update the platform to use the next environment by default.

**Comment by htlcnn** [comment]
@Amoki how do I know what environment my app is on? I have just created a new app. My `.env` content:
```
BD_APP_URL=http://localhost:8007
BD_OIDC_IP=https://iam-next.bimdata.io
BD_CONNECT_URL=https://iam-next.bimdata.io
BD_OIDC_CLIENT_ID=xxxx
BD_API_BASE_URL=https://api-next.bimdata.io
BD_CDN_BASE_URL=https://cdn-next.bimdata.io
BD_PLATFORM_BACK_BASE_URL=http://localhost:8008
BD_MAPBOX_TOKEN=pk.exxxx
BD_VIEWER_BASE_URL=https://viewer-next.bimdata.io
```
but I still had "Client not found" notification on https://iam-next.bimdata.io

**Comment by Amoki** [comment]
If you created your app on `connect.bimdata.io`, URLs are api.bimdata.io, iam.bimdata.io
If you created your app on `connect-next.bimdata.io`, URLs are api-next.bimdata.io, iam-next.bimdata.io

`next` is our pre-prod env. There is no SLA, IFC processes may be slower, but the latest features are there so you can test them.

**Comment by htlcnn** [comment]
I changed all to `*.bimdata.io` without `-next`. A page asked me to allow access. I accept and it falls back to and endless loop with different `state` and same `session_state` values in URL. For example:
```
http://10.15.0.30:8007/oidc-callback?state=f9b5aef4469c4910beed838057ff0926&session_state=85622c9e-20a2-4d7c-bb9d-29101a79c27d&code=2a7cbf24-cdd9-441e-9e92-c9a9acc14cdf.85622c9e-20a2-4d7c-bb9d-29101a79c27d.b99445ab-40c0-47ff-a87b-18a10dd73b32
http://10.15.0.30:8007/oidc-callback?state=5536350f3cd8462bb888d7c7adf50d48&session_state=85622c9e-20a2-4d7c-bb9d-29101a79c27d&code=8406a938-1884-4caa-b746-b23a6a8c6b3b.85622c9e-20a2-4d7c-bb9d-29101a79c27d.b99445ab-40c0-47ff-a87b-18a10dd73b32
```
(10.15.0.30 is my VM's VPN IP)

Btw, how could I use my own VM to process IFC? I installed IfcConvert, COLLADA2GLTF, gltf2xkt and xeokit-metadata and was able to generate xkt and json files via command line.

**Comment by Amoki** [comment]
You can open your browser debug toolbar to see more details about the problem.
The most current one is a misconfiguration of your app. Check if the access_type is "public" and the redirect_uris are valid

**Comment by Amoki** [comment]
You can't use your own process, you must use the API to do this.

**Comment by htlcnn** [comment]
I changed access_type from confidential to public and it worked. Thanks!
