### ISSUE TITLE
Problem deleting an IFC file

### ISSUE THREAD

**Issue by Francois-Thierry** [bimdata/platform-old#467]
On staging, when we try to delete a model from the IFC files it doesn't work right away.
## Description

Inside a project, when we try to delete an IFC from the list, the confirmation pop-up doesn't close after validation of the deletion, we have to wait a bit and then refresh the page to have it removed.
## Expected Behavior

When validating a deletion, the pop-up should close and the page should refresh (or update).
## Actual Behavior

We can't seem to be able to validate an IFC deletion, the *cancel* behavior is working.
## Possible Fix

.
## Steps to Reproduce

1. On the plateform (staging), go to one of your projects
2. Select one model from the IFC list and click on *action* (3 dots) then *delete* then *cancel* (red cross) to verify that the cancelation of deletion is working.
3. Click on *delete* and *validate* (green check) and experienced that the validation overlay doesn't close.
4. Click anywhere on the screen to deselect and/or refresh the page to see that the file is really deleted.

## Context

.
## Your Environment

* Version used: staging
* Browser Name and version: firefox
* Operating System and version (desktop or mobile): linux
* Link to your project, if relevant: .

**Comment by Amoki** [comment]
The deletion call to the API may be very long: we have to delete all properties, zones, property sets, and many objects. The solution should take place in the API imho
