### ISSUE TITLE
Local server didn't run

### ISSUE THREAD

**Issue by htlcnn** [bimdata/platform-old#495]
## Description
I edited the port from 8080 in package.json to 8007 (port 8080 was being used by other app) and `npm run serve`. The server didn't response.
Here is command line output:
```
╭─htl@u1804 ~/bimdata/platform ‹master*›
╰─$ npm run serve

> bimdata-platform@1.0.0 serve /home/htl/bimdata/platform
> NODE_OPTIONS=--max_old_space_size=4096 webpack-dev-server --progress --config build/webpack.config.dev.js --port 8007

10% building 3/4 modules 1 active ...oader/index.js?define=>false!/home/htl/bimdata/platform/node_modules/eslint-loader/index.js!/home/htl/bimdata/platform/src/main.jsBrowserslist: caniuse-lite is outdated. Please run next command `npm update`

```

## Expected Behavior
Server should be accessible on port 8007

## Actual Behavior
ERR_CONNECTION_REFUSED when I access port 8007

## Steps to Reproduce
Follow instructions in https://github.com/bimdata/platform/blob/develop/README.md

## Context
I wanted to install bimdata platform on my local machine.

## Your Environment
* Version used: newest git clone
* Browser Name and version: chrome 83.0.4103.116
* Operating System and version:
- Viewer: Windows 10 64-bit
- Server: Ubuntu 18.04 64-bit

**Comment by Amoki** [comment]
If I understand well, the `npm run serve` is not on the same machine as the browser?
Can it be a firewall that is only configured for 8080 or the reverse proxy is misconfigured?

**Comment by htlcnn** [comment]
No, it's not. I ran `npm run serve` on an Ubuntu virtual machine and accessed it on a Windows host machine. Access via VPN or LAN to Ubuntu VM's IP:8007 failed.
As you suggested, I tried and could access `localhost:8007` on Ubuntu VM.

ufw on Ubuntu VM is inactive:
```
╭─htl@u1804 ~
╰─$ sudo ufw status
Status: inactive
```

When I stopped bimdata platform on port 8007, I could start a `python3 -m http.server 8007` and accessed it via both VPN and LAN IP, so I think there was no firewall restriction or proxy misconfiguration.

**Comment by Amoki** [comment]
I think I have something.
By default, webpack-dev-server only allows localhost connections, which is not the case while using a VM.
Can you try to add `--host 0.0.0.0` here: https://github.com/bimdata/platform/blob/develop/package.json#L7 ?

**Comment by htlcnn** [comment]
Yes that's it. Thank you for your help. Do you have any config for production stage? I guess webpack-dev-server was meant for development stage.

**Comment by Amoki** [comment]
The command `npm run build` create a `dist` directory with the files you need to expose with nginx, apache, or any web-server.

The platform uses a router, meaning the URL does not match the real path of the file and all http queries must redirect to index.html.

You can find configurations example here: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-.
and our nginx config can be found here: https://github.com/bimdata/platform/blob/develop/etc/nginx.conf
