### ISSUE TITLE
README link broken: create application

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bimdata/platform-old#507]
Current broken (404) link is:

https://developers.bimdata.io/tutorials/dev_create_an_application.html

Should be pointing to:

https://developers.bimdata.io/api/introduction/quick_start.html#create-an-application

**Comment by Amoki** [comment]
Thanks!
Fixed by https://github.com/bimdata/platform/commit/3ef4fdaa25a7a294206d2c9d7db889348115328f
