### ISSUE TITLE
Resolving Few Issues

### ISSUE THREAD

**Issue by satyajitghana** [bimdata/platform-old#512]
1. Dependency Issues

I don't think it's well mentioned about the dependencies of the project, but it should have been.

```
node: 14.17.3
npm: 6.14.13
```

I've tried node 17, node 9, 10, and they dont work.

2. Npm Package Integrity Issue

Also when doing `npm install` you'll face issues with the package integrity verification of `vuex-oidc`, to solve this, simply open `package-lock.json` and search for `vuex-oidc`, and remove the `"integrity"` key, now run `npm install` again, it should work now

3. Accessing the host from other than `localhost`

Edit `package.json` 

in `"serve"` add these arguments `--host 0.0.0.0 --disable-host-check --port 8080`

**Comment by Amoki** [comment]
Hi, thanks for your interest in our platform.

This repo is soon to be archived, we completely rewrote the platform and you can find the code here: https://github.com/bimdata/platform-next
The install process is quite similar and the code is way cleaner.
