### ISSUE TITLE
collision

### ISSUE THREAD

**Issue by max482022** [bimdata/platform-old#519]
Good afternoon. How to implement collision search?

**Comment by Amoki** [comment]
Hello,
We do not provide collision functionalities yet. Sorry!

**Comment by max482022** [comment]
Is it possible to write a plugin to check for collisions? Is it real?

**Comment by Amoki** [comment]
Not in the viewer but be provide the geometries in the glTF format (a standard), and many libs allow you to do collisions with glTF geometries.
