### ISSUE TITLE
viewer

### ISSUE THREAD

**Issue by max482022** [bimdata/platform-old#520]
Is it possible to implement in bimdate viewer the opening of the model not by token, but that the model would be opened in gltf format in the viewer itself

**Comment by Amoki** [comment]
A gltf is not a model, just the geometries of the model.
Our viewer is made to be used with a token and the API.
With opening a gltf, you won't be able to use any property and interact with its objects (visibility, color, selection)

**Comment by max482022** [comment]
I can't figure out how to implement a free IFC model  viewer based on bimdata on my server. Without user registration. So that anyone can download the model and see

**Comment by Amoki** [comment]
BIMData viewer requires a license. But we provide On-premises solutions that can run on your servers.
You can find more information here: https://bimdata.io/en/bimdata-on-premise-solution

**Comment by Gubanov-482022** [comment]
And I can't put myself on a server with github. Or is a license required too?

**Comment by Amoki** [comment]
A license required too
