### ISSUE TITLE
Platform - accès compte et logout

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#57]
![image](https://user-images.githubusercontent.com/32667664/51035840-9e3e8880-15ab-11e9-8a03-0b51ef4d7b69.png)

![image](https://user-images.githubusercontent.com/32667664/51035854-a8608700-15ab-11e9-91fe-d8959180a333.png)

Un nouveau composant vient d'arriver sur la plateforme. Il faut désormais le mettre à jour niveau style CSS. 
J'ai testé un truc mais je suis pas certain pour la taille du texte par exemple. (ci-dessous) 

Si on peut mettre une petite animation au passage ça serait classe et vraiment cool :) 
https://projects.invisionapp.com/d/main#/console/16405056/340456867/preview

**Comment by jessyca27** [comment]
Doublon avec le ticket 71.
