### ISSUE TITLE
Platform - multi-upload GED

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#61]
![image](https://user-images.githubusercontent.com/32667664/51037688-2bd0a700-15b1-11e9-97b4-89c881424950.png)

Dans le cas de l'upload GED il faudrait permettre d'upload plusieurs fichiers ne même temps. (comme sur l'ancienne plateforme, même librairie).

**Comment by jessyca27** [comment]
Combien de fichiers max tu veux uploader ? (c'est un paramètre de l'outil que je dois mettre à jour :) )

**Comment by GabBimdata** [comment]
@jessyca27 toujours un bug à l'import il me re file des belles 404

**Comment by GabBimdata** [comment]
![image](https://user-images.githubusercontent.com/32667664/51321592-7b0c5100-1a63-11e9-937c-e2ca8edda506.png)

Hugo à troué d'ou ça vient ! On interverti l'id projet et l'id cloud.
