### ISSUE TITLE
Platform - titre page clouds

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#67]
![image](https://user-images.githubusercontent.com/32667664/51044076-89202480-15c0-11e9-8226-a69de5bc07a9.png)

https://projects.invisionapp.com/d/main#/console/16405056/340187190/preview

Peux-ont mettre un titre à cette page ? (cf. invision)

**Comment by jessyca27** [comment]
cette page la dispose d'un breadcrumb actuellement. Tu veux mettre le titre plutôt sur la toute première page d'accueil plutôt non ?

**Comment by GabBimdata** [comment]
Et bien c'est celle là ^^
![image](https://user-images.githubusercontent.com/32667664/51129222-2f229780-182a-11e9-867a-c7f8cffc27cd.png)

@jessyca27
