### ISSUE TITLE
Platform - fermeture modale GED

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#73]
![image](https://user-images.githubusercontent.com/32667664/51045810-cc7c9200-15c4-11e9-8f1f-1c70c106ad85.png)

Possible de pouvoir fermer la modale d'upload en cliquant dans le vide ? (en plus de la croix)

**Comment by benjaminaudet** [comment]
Moving back this issue to To-do because we will make our own uppy UI plugin that will avoid the usage of a modal
