### ISSUE TITLE
Platform - filtrer la GED en cliquant sur les titres des colonnes

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#74]
![image](https://user-images.githubusercontent.com/32667664/51045903-051c6b80-15c5-11e9-93a4-a9ce1c7918ed.png)

De manière assez similaire au tableau rapsotec, ça serait bien de pouvoir filtrer la GED par colonne dans le tableau.

**Comment by jessyca27** [comment]
Quels types de filtre veux-tu ?
- Les filtres ascendants/descendants ?
- ou des filtres particuliers ? --> auquel cas il faudrait qu'on les définissent ensemble avant que je m'y attaque :)
