### ISSUE TITLE
Platform - valider la recherche du "choicelist" avec la touche enter

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#86]
![image](https://user-images.githubusercontent.com/32667664/51172931-a7ce3600-18b4-11e9-8552-bfc5df7bfc1a.png)

Ça serait super intéressant de valider la recherche de projet et de cloud en tapant sur "entrer" :)

**Comment by jessyca27** [comment]
Vu avec Gab le 17/01/2019 : il faudrait sélectionner par défaut le premier élément de la liste
