### ISSUE TITLE
Platform - model preview : project cards

### ISSUE THREAD

**Issue by GabBimdata** [bimdata/platform-old#97]
![image](https://user-images.githubusercontent.com/32667664/51311116-7a19f600-1a48-11e9-887e-1c998bb00301.png)

The model preview component will be integrated into many places on the platform.
First, let's add it in the projects view.

To load a model preview, we need to load IFCs.
The idea is to load all projects (like today), then load project's IFCs asynchronously in a second time to not slow down the page.

If there is no Completed IFC's in the project, show the current placeholder.

For now, show the model preview of the first uploaded IFC.

https://projects.invisionapp.com/d/main#/console/16395807/341467848/preview

**Comment by VladislavGritsenko** [comment]
For now all works fine ^_^, but for later i advice to think about making some optimization:

1. Make on server small thumbnail for first slide of preview 360 image and add to api
2. Show this thumbnail by initial and asynchronously load 360 viewer on mouse hover.

this helps us decrease unnecessary requests (every request is a large image, for every project in list). for 10 projects is about 10-15mb of network traffic. 

What do you think?

**Comment by Amoki** [comment]
I just tried and it's not that bad! Your queries are very well optimized and each model-preview is just 100-300kb. Our customers usually have optic fiber as they are working from office buildings.
Once I have some time, I'll update the API to export a project thumbnail and meanwhile, we'll use this version :)
